language: java
install: true

jdk:
  - oraclejdk8

#before_script: cat /home/travis/build/luca-campanella/corda-flows-doc-builder/graph-builder/build/reports/tests/test/index.html

script:
  - ./gradlew build --scan -s --info

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/